# development overrides for compose.yml

services:
  root:
    build: .
    environment:
      HEALTH_CHECK_URL: http://localhost:7000

  get:
    build: .
    environment:
      HEALTH_CHECK_URL: http://localhost:7001

  see:
    environment:
      CORE_SECRET: development-secret
    volumes:
      - ./data/uploads:/zipline/uploads
      - ./data/public:/zipline/public
