# development overrides for compose.yml

x-app-config: &app-config
  APP_ZIPLINE_URL: http://see:7002

services:
  root:
    build: .
    environment:
      <<: *app-config
      HEALTH_CHECK_URL: http://localhost:7000

  see:
    environment:
      CORE_SECRET: development-secret
    volumes:
      - ./data/uploads:/zipline/uploads
      - ./data/public:/zipline/public
