version: 0.0
os: linux 
files:
  - source: /
    destination: /var/lib/codedeploy-apps/object-gay
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: hooks/application-stop.sh
      timeout: 60
  AfterInstall:
    - location: hooks/after-install.sh
      timeout: 120
  ApplicationStart:
    - location: hooks/application-start.sh
      timeout: 240
