version: 0.0
os: linux 
files:
  - source: /
    destination: /var/lib/codedeploy-apps/object.gay
  - source: ./object.gay.conf
    destination: /etc/apache2/sites-available
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/aws/application-stop.sh
      timeout: 60
  AfterInstall:
    - location: scripts/aws/after-install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/aws/application-start.sh
      timeout: 60
  ValidateService:
    - location: scripts/aws/validate-service.sh
      timeout: 60
