# production overrides for compose.yml

x-app-config: &app-config
  APP_ZIPLINE_URL: https://see.object.gay

services:
  root:
    image: "ghcr.io/object-object/object.gay@${IMAGE_ID}"
    environment:
      <<: *app-config
      HEALTH_CHECK_URL: https://object.gay

  see:
    environment:
      CORE_SECRET: "${ZIPLINE_SECRET}"
    volumes:
      - /mnt/blockstorage/codedeploy-apps/object-gay/uploads:/zipline/uploads
      - /mnt/blockstorage/codedeploy-apps/object-gay/public:/zipline/public
      - /mnt/blockstorage/codedeploy-apps/object-gay/themes:/zipline/themes
