name: Build and deploy

on:
  push:
    branches: main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  NODE_VERSION: 18

jobs:
  # TODO: similar setup for terraform
  build-aws-cdk:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: object-Object/ci/setup@v0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          python-packages: nox
          node-version: ${{ env.NODE_VERSION }}
          npm-packages: aws-cdk
      
      - name: Synthesize stack and build package
        run: nox -t build

      - name: Upload synth artifact
        uses: actions/upload-artifact@v4
        with:
          name: synth
          path: cdk.out

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy-aws-cdk:
    needs: build-aws-cdk
    runs-on: ubuntu-latest
    environment:
      name: prod-aws-cdk
    permissions:
      id-token: write
      contents: read
    outputs:
      stack-name: ${{ steps.deploy.outputs.StackName }}
      application-name: ${{ steps.deploy.outputs.ApplicationName }}
      deployment-group-name: ${{ steps.deploy.outputs.DeploymentGroupName }}
      iam-role-arn: ${{ steps.deploy.outputs.ActionsCodeDeployRoleARN }}
      artifacts-bucket-name: ${{ steps.deploy.outputs.ArtifactsBucketName }}
    steps:
      - uses: actions/checkout@v4
      - uses: object-Object/ci/setup@v0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          python-packages: nox
          node-version: ${{ env.NODE_VERSION }}
          npm-packages: aws-cdk
          role-to-assume: default

      - name: Download synth artifact
        uses: actions/download-artifact@v4
        with:
          name: synth
          path: cdk.out

      - name: Deploy CDK stack
        id: deploy
        run: nox -s deploy_cdk_ci -- prod

  deploy-terraform:
    runs-on: ubuntu-latest
    environment:
      name: prod-terraform
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: object-Object/ci/setup@v0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          python-packages: -e .[terraform]
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v1
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          mode: auto-approve-apply
          stackName: prod
          terraformCloudToken: ${{ secrets.TERRAFORM_CLOUD_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
